# build description for travis-ci.org
language: java
jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7
  - openjdk6

script: mvn verify

services:
  - mysql
  - postgresql
before_script:
  - mysql -e 'create database presage_test;' # mysql test database
  - psql -c 'create database presage_test' -U postgres # postgres test database
